# Generated by Django 4.1 on 2023-12-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expenses",
            name="amount",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="category",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="desc",
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name="expenses",
            name="timestamp",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
